# TCL File Generated by Component Editor 11.0sp1
# Wed Jan 18 08:54:24 JST 2012
# DO NOT MODIFY


# +-----------------------------------
# | 
# | pwm_avalon "pwm_avalon" v1.0
# | null 2012.01.18.08:54:24
# | 
# | 
# | C:/home/quartus/Nios2_MemoryMapLib_SDRAM/hdl/pwm_avalon.v
# | 
# |    ./pwm_avalon.v syn, sim
# |    ./pwm.v syn, sim
# |    ./dff.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module pwm_avalon
# | 
set_module_property NAME pwm_avalon
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME pwm_avalon
set_module_property TOP_LEVEL_HDL_FILE pwm_avalon.v
set_module_property TOP_LEVEL_HDL_MODULE PWM8_avalon_busif
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME PWM8_avalon_busif
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file pwm_avalon.v {SYNTHESIS SIMULATION}
add_file pwm.v {SYNTHESIS SIMULATION}
add_file dff.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 0

set_interface_property clock ENABLED true
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset
# | 
add_interface reset reset end
set_interface_property reset associatedClock clock_sink
set_interface_property reset synchronousEdges DEASSERT

set_interface_property reset ENABLED true
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0
# | 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressAlignment NATIVE
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 isMemoryDevice false
set_interface_property avalon_slave_0 isNonVolatileStorage false
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 printableDevice false
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitStates 2
set_interface_property avalon_slave_0 writeWaitTime 2

set_interface_property avalon_slave_0 ENABLED true

add_interface_port avalon_slave_0 address address Input 2
add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 writedata writedata Input 8
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_sink
# | 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0

set_interface_property clock_sink ENABLED true

add_interface_port clock_sink clk clk Input 1
add_interface_port clock_sink reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ENABLED true

add_interface_port conduit_end value1 export Output 8
add_interface_port conduit_end value2 export Output 8
add_interface_port conduit_end pwmout1 export Output 1
add_interface_port conduit_end pwmout2 export Output 1
# | 
# +-----------------------------------
